# Generated by Django 3.1.13 on 2021-08-18 22:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
